### ISSUE TITLE
BUG: Can't WriteObject a byte array (InvalidCastException)

### ISSUE THREAD

**Issue by micdenny** [Syroot/BinaryData#11]
This should be hot fixed:

Exception: InvalidCastException: Unable to cast object of type 'System.Byte' to type 'System.Collections.IEnumerable'.

Repro:

```csharp
void Main()
{
	var mtc = new MyTestClass();
	
	byte[] bytes;
	using (var stream = new MemoryStream())
	{
		stream.WriteObject(mtc, ByteConverter.BigEndian);
		bytes = stream.ToArray();
	}
}

[BinaryObject(Explicit = true)]
public class MyTestClass
{
	[BinaryMember(Order = 1, Length = 3)]
	public byte[] Free { get; set; } = new byte[3];
}
```

**Comment by micdenny** [comment]
here's the right point [StreamExtensions.Writing.cs#L732](https://github.com/Syroot/BinaryData/blob/master/src/Syroot.BinaryData/Extensions/StreamExtensions.Writing.cs#L732)

![image](https://user-images.githubusercontent.com/1633595/34532725-70849e1c-f0b7-11e7-9aa6-f51361d6dcc3.png)

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.Byte' to type 'System.Collections.IEnumerable'.
  Source=Syroot.BinaryData
  StackTrace:
   at Syroot.BinaryData.Extensions.StreamExtensions.WriteObject(Stream stream, Object instance, BinaryMemberAttribute attribute, Type type, Object value, ByteConverter converter) in D:\Users\micde\Documents\Git\BinaryData\src\Syroot.BinaryData\Extensions\StreamExtensions.Writing.cs:line 732
   at Syroot.BinaryData.Extensions.StreamExtensions.WriteMember(Stream stream, Object instance, Int64 startOffset, ByteConverter converter, MemberData member) in D:\Users\micde\Documents\Git\BinaryData\src\Syroot.BinaryData\Extensions\StreamExtensions.Writing.cs:line 874
   at Syroot.BinaryData.Extensions.StreamExtensions.WriteCustomObject(Stream stream, Type type, Object instance, Int64 startOffset, ByteConverter converter) in D:\Users\micde\Documents\Git\BinaryData\src\Syroot.BinaryData\Extensions\StreamExtensions.Writing.cs:line 823
   at Syroot.BinaryData.Extensions.StreamExtensions.WriteObject(Stream stream, Object instance, BinaryMemberAttribute attribute, Type type, Object value, ByteConverter converter) in D:\Users\micde\Documents\Git\BinaryData\src\Syroot.BinaryData\Extensions\StreamExtensions.Writing.cs:line 796
   at Syroot.BinaryData.Extensions.StreamExtensions.WriteMember(Stream stream, Object instance, Int64 startOffset, ByteConverter converter, MemberData member) in D:\Users\micde\Documents\Git\BinaryData\src\Syroot.BinaryData\Extensions\StreamExtensions.Writing.cs:line 868
   at Syroot.BinaryData.Extensions.StreamExtensions.WriteCustomObject(Stream stream, Type type, Object instance, Int64 startOffset, ByteConverter converter) in D:\Users\micde\Documents\Git\BinaryData\src\Syroot.BinaryData\Extensions\StreamExtensions.Writing.cs:line 823
   at Syroot.BinaryData.Extensions.StreamExtensions.WriteCustomObject(Stream stream, Type type, Object instance, Int64 startOffset, ByteConverter converter) in D:\Users\micde\Documents\Git\BinaryData\src\Syroot.BinaryData\Extensions\StreamExtensions.Writing.cs:line 817
   at Syroot.BinaryData.Extensions.StreamExtensions.WriteObject(Stream stream, Object instance, BinaryMemberAttribute attribute, Type type, Object value, ByteConverter converter) in D:\Users\micde\Documents\Git\BinaryData\src\Syroot.BinaryData\Extensions\StreamExtensions.Writing.cs:line 796
   at Syroot.BinaryData.Extensions.StreamExtensions.WriteObject(Stream stream, Object value, ByteConverter converter) in D:\Users\micde\Documents\Git\BinaryData\src\Syroot.BinaryData\Extensions\StreamExtensions.Writing.cs:line 388
   at Aams.Psqf.Client.Tests.DisciplineRequestSerializerTests.WriteObject_a_discipline_request_with_inizio_and_fine_set_should_produce_the_correct_byte_array() in C:\Engage\AamsPsqfClient\test\Aams.Psqf.Client.Tests\Serializers\DisciplineRequestSerializerTests.cs:line 188
```

**Comment by RayKoopa** [comment]
I wonder why `TryGetEnumerableType` returns `true` there. Will be added to the next fix in 2 weeks.

**Comment by micdenny** [comment]
> I wonder why TryGetEnumerableType returns true there

because the `type` is in fact an `Byte[]` where it should be a `byte` when calling WriteObject here:

![image](https://user-images.githubusercontent.com/1633595/34532853-0b228f9c-f0b8-11e7-88bc-98ccaacc0402.png)

```csharp
                foreach (object element in (IEnumerable)value)
                {
                    WriteObject(stream, instance, member.Attribute, member.Type, element, converter);
                }
```

**Comment by micdenny** [comment]
could it be fixed by simply do this?

```csharp
WriteObject(stream, instance, member.Attribute, element.GetType(), element, converter);
```

**Comment by micdenny** [comment]
ops sorry there's also `elementType` that can be used and it performs better, so it becomes:

```csharp
WriteObject(stream, instance, member.Attribute, elementType, element, converter);
```

**Comment by RayKoopa** [comment]
Yeah, I really have dejavu's with the last problems fixed, including this one. It feels like I fixed them some time ago, but the commit including them never got pushed... weird. Anyway, that's exactly the way it should be.

**Comment by micdenny** [comment]
great thank you!

**Comment by RayKoopa** [comment]
There'll be a prerelease version you can download until I make it RTM, just in case more of these weird errors pop up in the next two weeks.

**Comment by RayKoopa** [comment]
Fixed with https://github.com/Syroot/BinaryData/commit/caaa213c871374e616a12bc5b199b666569efa23
