### ISSUE TITLE
Question: how to manage an optional property using ReadObject

### ISSUE THREAD

**Issue by micdenny** [Syroot/BinaryData#13]
I have classes that are uniquely identified by an ID, and those classes are used as properties on a master class `Message`, this properties are in fact optional and could be in different order.

This is the sample classes:

```csharp
[BinaryObject(Explicit = true)]
public class Message
{
	[BinaryMember(Order = 1)]
	public ushort SomethingShort { get; set; }

	[BinaryMember(Order = 2)]
	public OptionalOne OptionalOne { get; set; }

	[BinaryMember(Order = 3)]
	public OptionalTwo OptionalTwo { get; set; }

	[BinaryMember(Order = 4)]
	public OptionalThree OptionalThree { get; set; }
}

[BinaryObject(Explicit = true)]
public class OptionalOne
{
	[BinaryMember(Order = 1)]
	public ushort Id { get; set; } = 1;

	[BinaryMember(Order = 2)]
	public byte Len { get; set; } = 4;

	[BinaryMember(Order = 3)]
	public ushort Start { get; set; }

	[BinaryMember(Order = 4)]
	public ushort Stop { get; set; }
}

[BinaryObject(Explicit = true)]
public class OptionalTwo
{
	[BinaryMember(Order = 1)]
	public ushort Id { get; set; } = 2;

	[BinaryMember(Order = 2)]
	public byte Len { get; set; } = 8;

	[BinaryMember(Order = 3)]
	public ulong Size { get; set; }
}

[BinaryObject(Explicit = true)]
public class OptionalThree
{
	[BinaryMember(Order = 1)]
	public ushort Id { get; set; } = 3;

	[BinaryMember(Order = 2)]
	public byte Len { get; set; } = 3;

	[BinaryMember(Order = 3)]
	public byte X { get; set; }

	[BinaryMember(Order = 4)]
	public byte Y { get; set; }

	[BinaryMember(Order = 5)]
	public byte Z { get; set; }
}
```

and let's say that I want to Write and the Read this object:

```csharp
var message = new Message
{
    SomethingShort = 1234,
    OptionalTwo = new OptionalTwo
    {
        Size = 555
    }
};
```

I'm able to let this work by creating one `Converter` for every optional class:

```csharp
public class OptionalOneConverter : IBinaryConverter
{
    public object Read(Stream stream, object instance, BinaryMemberAttribute memberAttribute, ByteConverter converter)
    {
        if (stream.IsEndOfStream())
        {
            return null;
        }
        ushort id;
        using (stream.TemporarySeek())
        {
            id = stream.ReadUInt16(converter);
        }
        if (id == 1)
        {
            return stream.ReadObject<OptionalOne>(converter);
        }
        return null;
    }

    public void Write(Stream stream, object instance, BinaryMemberAttribute memberAttribute, object value, ByteConverter converter)
    {
        if (value != null)
        {
            stream.WriteObject(value, converter);
        }
    }
}

public class OptionalTwoConverter : IBinaryConverter
{
    public object Read(Stream stream, object instance, BinaryMemberAttribute memberAttribute, ByteConverter converter)
    {
        if (stream.IsEndOfStream())
        {
            return null;
        }
        ushort id;
        using (stream.TemporarySeek())
        {
            id = stream.ReadUInt16(converter);
        }
        if (id == 2)
        {
            return stream.ReadObject<OptionalTwo>(converter);
        }
        return null;
    }

    public void Write(Stream stream, object instance, BinaryMemberAttribute memberAttribute, object value, ByteConverter converter)
    {
        if (value != null)
        {
            stream.WriteObject(value, converter);
        }
    }
}

public class OptionalThreeConverter : IBinaryConverter
{
    public object Read(Stream stream, object instance, BinaryMemberAttribute memberAttribute, ByteConverter converter)
    {
        if (stream.IsEndOfStream())
        {
            return null;
        }
        ushort id;
        using (stream.TemporarySeek())
        {
            id = stream.ReadUInt16(converter);
        }
        if (id == 3)
        {
            return stream.ReadObject<OptionalThree>(converter);
        }
        return null;
    }

    public void Write(Stream stream, object instance, BinaryMemberAttribute memberAttribute, object value, ByteConverter converter)
    {
        if (value != null)
        {
            stream.WriteObject(value, converter);
        }
    }
}
```

*but do you think there is a better way to do this?* I would like to avoid writing a converter for every optional class but the `IBinaryConverter` doesn't provide the reflected property but only the attribute, so at that point it seems I can't know which class Type I'm referring to, but I'm feeling there's a better way to do this but I can't visualize it 😄

**Comment by RayKoopa** [comment]
I recommend using `Message` as a base class and make the specific classes child classes of it, which only stores properties common to all - excluding the ID.
Then you require a factory method to read the identifier (which is not part of the base class) and instantiate the right class accordingly.
That's how I did it with SDL and X11 messages at least.

**Comment by micdenny** [comment]
Can you be so kind to show me an example, would be much appreciated

**Comment by RayKoopa** [comment]
I'm not at home, but out of my head:
```cs
[BinaryObject(Explicit = true)]
public abstract class Message
{
    [BinaryMember(Order = 1)]
    public byte Len { get; set; };
    [BinaryMember(Order = 2)]
    public ushort SomethingShort { get; set; } // Given this value is available in all messages

    public static Message Instantitate(Stream stream)
    {
        switch (stream.ReadUInt16())
        {
            case 1:
                return stream.ReadObject<MessageOne>();
                break;
            case 2:
                return stream.ReadObject<MessageTwo>();
                break;
            case 3:
                return stream.ReadObject<MessageThree>();
                break;
        }
    }
}

[BinaryObject(Explicit = true, Inherited = true)]
public class MessageOne : Message
{
    [BinaryMember(Order = 3)]
    public ushort Start { get; set; }
    [BinaryMember(Order = 4)]
    public ushort Stop { get; set; }
}

[BinaryObject(Explicit = true, Inherited = true)]
public class MessageTwo : Message
{
	[BinaryMember(Order = 3)]
	public ulong Size { get; set; }
}

[BinaryObject(Explicit = true, Inherited = true)]
public class MessageThree : Message
{
	[BinaryMember(Order = 3)]
	public byte X { get; set; }
	[BinaryMember(Order = 4)]
	public byte Y { get; set; }
	[BinaryMember(Order = 5)]
	public byte Z { get; set; }
}
``

**Comment by micdenny** [comment]
The problem is that all or none can be in the message, not just one of those.

I'm trying a solution using an array, even if it adds a null element when I return null from the BinaryConverter, but that's easy to manage later on.

**Comment by RayKoopa** [comment]
Then you have to write manual code managing that.

**Comment by micdenny** [comment]
yes sure:

```csharp
using System;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;
using Syroot.BinaryData;
using Syroot.BinaryData.Extensions;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            var message = new MessageWithList
            {
                Numbers = new List<ushort> { 123, 32, 12 }
            };

            Console.WriteLine(JsonConvert.SerializeObject(message, Formatting.Indented));

            Console.WriteLine();
            Console.WriteLine();

            byte[] bytes;
            using (var stream = new MemoryStream())
            {
                stream.WriteObject(message);
                bytes = stream.ToArray();
            }
            
            for (int i = 0; i < bytes.Length; i++)
            {
                Console.WriteLine($"[{i}]={bytes[i]}");
            }

            Console.WriteLine();
            Console.WriteLine();

            MessageWithList m;
            using (var stream = new MemoryStream(bytes))
            {
                m = stream.ReadObject<MessageWithList>();
            }
            Console.WriteLine(JsonConvert.SerializeObject(m, Formatting.Indented));
        }
    }

    [BinaryObject(Explicit = true)]
    public class MessageWithList
    {
        [BinaryMember(Order = 1, Length = 3)]
        public List<ushort> Numbers { get; set; }
    }

    [BinaryObject(Explicit = true)]
    public class MessageWithArray
    {
        [BinaryMember(Order = 1, Length = 3)]
        public ushort[] Numbers { get; set; }
    }
}
```

if you run with `MessageWithArray` everything's fine, instead if you run with `MessageWithList` you get the exception:

```
Unhandled Exception: System.ArgumentException: Object of type 'System.UInt16[]' cannot be converted to type 'System.Collections.Generic.List`1[System.UInt16]'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Syroot.BinaryData.Extensions.StreamExtensions.ReadMember(Stream stream, Object instance, Int64 startOffset, ByteConverter converter, MemberData member)
   at Syroot.BinaryData.Extensions.StreamExtensions.ReadCustomObject(Stream stream, Type type, Object instance, Int64 startOffset, ByteConverter converter)
   at Syroot.BinaryData.Extensions.StreamExtensions.ReadObject(Stream stream, Object instance, BinaryMemberAttribute attribute, Type type, ByteConverter converter)
   at Syroot.BinaryData.Extensions.StreamExtensions.ReadObject[T](Stream stream, ByteConverter converter)
   at ConsoleApp3.Program.Main(String[] args) in ConsoleApp3\ConsoleApp3\Program.cs:line 42
```

**Comment by RayKoopa** [comment]
Wrong issue, but I replied to the right one. Is there anything else to add to this question?

**Comment by micdenny** [comment]
> Wrong issue, but I replied to the right one.

I've moved the wrong comment in the right issue 😄 

> Is there anything else to add to this question?

I would like to share my solution then close it.

**Comment by micdenny** [comment]
This is my solution for this issue.

This version supports optional and unordered values that belongs to the same interfacem when you have something like extended attributes, and you don't know upfront how many of those you have and the order is not mandatory:

https://gist.github.com/micdenny/b67e38a0455c22a8429cb2890a5f6d31
